export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_USER = 'SET_USER';
export const SET_PROFILE = 'SET_PROFILE';
export const CLEAR_CURRENT_STATE = 'CLEAR_CURRENT_STATE';
export const SET_LOADING = 'SET_LOADING';
export const SET_PROFILES = 'SET_PROFILES';
